"""initial schema

Revision ID: 22285d36f29a
Revises: 
Create Date: 2026-04-30 21:18:11.611100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '22285d36f29a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Extensions used by the platform (§3.8).
    # pgvector is not enabled here — added in the chatbot's bring-up migration (Sprint 9).
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_user_date', 'audit_log', ['user_id', 'occurred_at'], unique=False)
    op.create_table('forex_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.String(length=10), nullable=False),
    sa.Column('to_currency', sa.String(length=10), server_default='INR', nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('effective_date', 'from_currency', 'to_currency', name='uq_forex_rate_per_day')
    )
    op.create_table('mis_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=20), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='Pending', nullable=False),
    sa.Column('source_file_url', sa.String(length=512), nullable=True),
    sa.Column('source_file_name', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('anomaly_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period_year', 'period_month', name='uq_mis_submission_period')
    )
    op.create_table('portfolio_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('portfolio_type', sa.String(length=50), nullable=True),
    sa.Column('investment_status', sa.String(length=30), nullable=True),
    sa.Column('portfolio_status', sa.String(length=20), nullable=True),
    sa.Column('asset_class', sa.String(length=30), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('sub_sector', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('date_of_first_investment', sa.Date(), nullable=True),
    sa.Column('investment_value_cr', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('current_value_cr', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('moic', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('irr', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=10), server_default='INR', nullable=False),
    sa.Column('primary_contact_id', sa.Integer(), nullable=True),
    sa.Column('reporting_frequency', sa.String(length=20), server_default='Monthly', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_portfolio_sector', 'portfolio_companies', ['sector'], unique=False)
    op.create_index('idx_portfolio_status', 'portfolio_companies', ['portfolio_status', 'investment_status'], unique=False)
    op.create_index('idx_portfolio_type', 'portfolio_companies', ['portfolio_type'], unique=False)
    op.create_table('mis_bu_monthly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=20), nullable=True),
    sa.Column('bu_id', sa.String(length=20), nullable=True),
    sa.Column('month_date', sa.Date(), nullable=True),
    sa.Column('fiscal_year', sa.String(length=10), nullable=True),
    sa.Column('quarter', sa.String(length=5), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('revenue_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('cogs_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('gross_margin_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('gross_margin_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('operating_costs_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ebitda_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ebitda_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('channel_dine_in_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('channel_aggregator_a_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('channel_aggregator_b_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('channel_aggregator_d_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('channel_catering_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('channel_franchise_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['mis_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'bu_id', 'month_date', name='uq_mis_bu_monthly_period')
    )
    op.create_table('mis_monthly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=20), nullable=True),
    sa.Column('month_date', sa.Date(), nullable=True),
    sa.Column('fiscal_year', sa.String(length=10), nullable=True),
    sa.Column('quarter', sa.String(length=5), nullable=True),
    sa.Column('geography', sa.String(length=30), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('revenue_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('indirect_income_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_income_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('cogs_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('gross_margin_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('gross_margin_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('total_operating_costs_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('manpower_cost_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('rent_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('utilities_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('electricity_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('channel_expenses_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('commission_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('transport_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('marketing_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('admin_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('it_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('professional_fees_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('compliance_costs_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('events_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ebitda_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ebitda_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('itc_reversal_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ebitda_with_itc_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['mis_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'month_date', 'geography', name='uq_mis_monthly_period_geo')
    )
    op.create_index('idx_mis_monthly_company_date', 'mis_monthly', ['company_id', 'month_date'], unique=False)
    op.create_table('mis_outlet_monthly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=20), nullable=True),
    sa.Column('bu_id', sa.String(length=20), nullable=True),
    sa.Column('outlet_id', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.Column('month_date', sa.Date(), nullable=True),
    sa.Column('area_sqft', sa.Integer(), nullable=True),
    sa.Column('covers', sa.Integer(), nullable=True),
    sa.Column('sales_to_rent_ratio', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('revenue_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('cogs_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('gross_margin_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('gross_margin_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('operating_costs_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('operational_profit_lacs', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('operational_profit_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['mis_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('amount_cr', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('original_currency', sa.String(length=10), server_default='INR', nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('amount_inr_cr', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('fx_rate_used', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('series', sa.String(length=64), nullable=True),
    sa.Column('instrument_type', sa.String(length=64), nullable=True),
    sa.Column('investing_entity', sa.String(length=128), nullable=True),
    sa.Column('shares', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('share_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('pre_money_valuation_cr', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('post_money_valuation_cr', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('shareholding_pct', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('ssa_reference', sa.String(length=255), nullable=True),
    sa.Column('ssa_recorded_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['portfolio_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_portfolio_transactions_company_date', 'portfolio_transactions', ['company_id', 'transaction_date'], unique=False)
    op.create_table('reminder_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('cadence_days', sa.Integer(), server_default='7', nullable=False),
    sa.Column('first_reminder_offset_days', sa.Integer(), server_default='5', nullable=False),
    sa.Column('escalation_threshold', sa.Integer(), server_default='3', nullable=False),
    sa.Column('escalation_contact_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['portfolio_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['portfolio_companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reminder_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='Sent', nullable=False),
    sa.Column('is_escalation', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('related_period', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['reminder_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reminder_company_period', 'reminder_log', ['company_id', 'related_period'], unique=False)
    # ### end Alembic commands ###

    # Aggregated portfolio rollups (§3.7).
    # Refreshed every 5 minutes by a Celery task (added in Sprint 6).
    op.execute(
        """
        CREATE MATERIALIZED VIEW portfolio_aggregates_mv AS
        SELECT
            'TOTAL'::text AS scope_type,
            NULL::text    AS scope_value,
            SUM(ABS(investment_value_cr)) AS total_invested_cr,
            SUM(current_value_cr)         AS current_value_cr,
            SUM(current_value_cr) / NULLIF(SUM(ABS(investment_value_cr)), 0) AS moic,
            COUNT(*) AS company_count
        FROM portfolio_companies WHERE is_active = TRUE
        UNION ALL
        SELECT 'SECTOR', sector,
            SUM(ABS(investment_value_cr)), SUM(current_value_cr),
            SUM(current_value_cr) / NULLIF(SUM(ABS(investment_value_cr)), 0),
            COUNT(*)
        FROM portfolio_companies WHERE is_active = TRUE GROUP BY sector
        UNION ALL
        SELECT 'PORTFOLIO_TYPE', portfolio_type,
            SUM(ABS(investment_value_cr)), SUM(current_value_cr),
            SUM(current_value_cr) / NULLIF(SUM(ABS(investment_value_cr)), 0),
            COUNT(*)
        FROM portfolio_companies WHERE is_active = TRUE GROUP BY portfolio_type;
        """
    )
    op.execute(
        "CREATE UNIQUE INDEX idx_pa_mv_scope ON portfolio_aggregates_mv(scope_type, scope_value);"
    )


def downgrade() -> None:
    # Drop the matview before its underlying tables.
    op.execute("DROP MATERIALIZED VIEW IF EXISTS portfolio_aggregates_mv;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reminder_company_period', table_name='reminder_log')
    op.drop_table('reminder_log')
    op.drop_table('users')
    op.drop_table('reminder_schedules')
    op.drop_index('idx_portfolio_transactions_company_date', table_name='portfolio_transactions')
    op.drop_table('portfolio_transactions')
    op.drop_table('mis_outlet_monthly')
    op.drop_index('idx_mis_monthly_company_date', table_name='mis_monthly')
    op.drop_table('mis_monthly')
    op.drop_table('mis_bu_monthly')
    op.drop_index('idx_portfolio_type', table_name='portfolio_companies')
    op.drop_index('idx_portfolio_status', table_name='portfolio_companies')
    op.drop_index('idx_portfolio_sector', table_name='portfolio_companies')
    op.drop_table('portfolio_companies')
    op.drop_table('mis_submissions')
    op.drop_table('forex_rates')
    op.drop_index('idx_audit_user_date', table_name='audit_log')
    op.drop_index('idx_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
